AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - './bin/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'actionmessenger.gemspec'
    - './lib/action_messenger/templates/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
